version: '3.9'

services:
  nutrition_facts_api:
    build: .
    container_name: nutrition_facts_api
    restart: always
    depends_on:
      nutrition_facts_postgres:
        condition: service_healthy
      nutrition_facts_chroma:
        condition: service_started
    env_file:
      - .env
    environment:
      FIREBASE_CREDENTIAL_PATH: "/app/firebase-adminsdk.json"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nutrition_facts_postgres:5432/${POSTGRES_DB}"
      CHROMA_HOST: nutrition_facts_chroma
      CHROMA_PORT: 8000
      TRANSFORMERS_CACHE: /app/models_cache
    volumes:
      - ./:/app
      - ./secrets/firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
      - huggingface_cache:/app/models_cache
    ports:
      - "8000:8000"

  nutrition_facts_chroma:
    image: chromadb/chroma:latest
    container_name: nutrition_facts_chroma
    restart: always
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8001:8000"

  nutrition_facts_postgres:
    image: postgres:15
    container_name: nutrition_facts_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  chroma_data:
  huggingface_cache: